ALTER TABLE users ADD COLUMN last_latitude DECIMAL(10,8) DEFAULT NULL;
ALTER TABLE users ADD COLUMN last_longitude DECIMAL(11,8) DEFAULT NULL;
ALTER TABLE users ADD COLUMN last_location_at DATETIME DEFAULT NULL;
